services:
  my-api:
    build:
      context: .
      target: development
    ports:
      - '4500:4500'
    env_file:
      - ./.env
    volumes:
      - type: bind
        source: ${APPDATA}/gcloud/application_default_credentials.json
        target: /root/.config/gcloud/application_default_credentials.json
        read_only: true
    develop:
      watch:
        - path: .
          action: sync
          target: /usr/src/app
          ignore:
            - node_modules/
            - .git/
            - .env
        - path: package.json
          action: rebuild
        - path: pnpm-lock.yaml
          action: rebuild
